### PR TITLE
Splash Screen

### PR DESCRIPTION
**Pull request by ahamedmh**

### CODE REVIEW

**Comment by mohancm** [comment]
@anonheartbeat  provide your slack id

**Comment by ahamedmh** [comment]
@HeartBeat

**Comment by ahamedmh** [comment]
anonheartbeat in GitHub is same as @HeartBeat in slack...same name

**Comment by mohancm** [comment]
@anonheartbeat provide some screenshots or video of your work

**Comment by mohancm** [comment]
??

**Comment by ahamedmh** [comment]
I have already send it in early message.....but photo didn't come in the
channel..

**Comment by ahamedmh** [comment]
pls tell me u got it...
or I uploaded in channel

**Pull request closed without merging**
