### PR TITLE
Splash

### PR DESCRIPTION
**Pull request by rohitvivek**
Splash

### CODE REVIEW

**Comment by rohitvivek** [comment]
Splash screen

**Comment by mohancm** [comment]
@rohitvivek please attach some screenshots of your work

**Comment by rohitvivek** [comment]
screenshot_1524034695

**Comment by rohitvivek** [comment]
giphy

**Comment by mohancm** [comment]
Can you make that text animated?

**Comment by rohitvivek** [comment]
sure :)

**Comment by rohitvivek** [comment]
giphy 2

**Comment by mohancm** [comment]
Looks fine now, 
Use Google San font for text and any other animation for text?

**Comment by rohitvivek** [comment]
blink

**Comment by rohitvivek** [comment]
@mohancm like you suggested  i have made the following changes ,have used google sans italic font for the splash screen text with different animation 
giphy

**Comment by mohancm** [comment]
ok thanks

**Pull request closed without merging**
